version: "3.3"

services:
  db:
    image: mysql:5.7
    volumes:
      - ./.docker/schema/:/docker-entrypoint-initdb.d
      - ./.docker/datadir/mysql:/var/lib/mysql
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    
    # Disable mysql strict mode
    # --max_allowed_packet=1000M #256M
    command: mysqld --sql_mode="" 
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3306:3306"

  wordpress:
    depends_on:
      - db
    build:
      context: .docker/docker
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./html/:/var/www/html/
      - ./.docker/php/php.ini:/usr/local/etc/php/php.ini
    environment:
      #Enable PHP Debugging
      PHP_EXTENSION_XDEBUG: 1
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_SITE_URL: 'http://localhost'
      WORDPRESS_DB_HOME_URL: 'http://localhost'
      WORDPRESS_DB_PREFIX: 'wp_'
    

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8181:80
    environment:
      UPLOAD_LIMIT: 1000M
